Giants Configuration:
  File Version: Version
  Entities:
    Giant: true
    Giant Slime: false
    Giant Magma Cube: false
    Giant Jockey:
      Warning:
        Bugs: This entity of Giants is extremely experimental and does not have many features. Bugs may be present.
        Files: Config files for this entity will NOT load unless enabled.
        Enabled: false
  Debug Mode:
    Enabled: false
    Debug Message: '&2A {entity} has spawned at X:&F%X &2Y:&F%Y &2Z:&F%Z'
  PluginMetrics:
    Enabled: true
