Giants Configuration:
  Entities:
    Giant: false
    Giant Slime: false
    Giant Magma Cube: false
  Debug Mode: false
  Language:
    Debug Message: '&2A {entity} has spawned at X:&F%X &2Y:&F%Y &2Z:&F%Z'
